### ISSUE TITLE
Installing iso, add btrfs support

### ISSUE THREAD

**Issue by archey** [ArchStrike/archstrike-iso#3]
DEBUG - Gen Initramfs
DEBUG - arch-chroot /mnt mkinitcpio -p linux
INFO - ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
INFO - -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
INFO - ==> Starting build: 4.7.6-1-ARCH
INFO - -> Running build hook: [base]
INFO - -> Running build hook: [udev]
INFO - -> Running build hook: [autodetect]
INFO - -> Running build hook: [modconf]
INFO - -> Running build hook: [block]
INFO - -> Running build hook: [filesystems]
INFO - -> Running build hook: [keyboard]
INFO - -> Running build hook: [fsck]
ERROR - ==> ERROR: file not found: `fsck.btrfs'
ERROR - ==> WARNING: No fsck helpers found. fsck will not be run on boot.
INFO - ==> Generating module dependencies
INFO - ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
ERROR - ==> WARNING: errors were encountered during the build. The image may not be complete.
INFO - ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
INFO - -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
INFO - ==> Starting build: 4.7.6-1-ARCH
INFO - -> Running build hook: [base]
INFO - -> Running build hook: [udev]
INFO - -> Running build hook: [modconf]
INFO - -> Running build hook: [block]
ERROR - ==> WARNING: Possibly missing firmware for module: wd719x
ERROR - ==> WARNING: Possibly missing firmware for module: aic94xx
INFO - -> Running build hook: [filesystems]
INFO - -> Running build hook: [keyboard]
INFO - -> Running build hook: [fsck]
INFO - ==> Generating module dependencies
INFO - ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
INFO - ==> Image generation successful
ERROR - arch-chroot /mnt mkinitcpio -p linux

**Comment by archey** [comment]
@ahtss can you give us more information from the output, I assume you were trying to install from the iso correct?

**Comment by ahtss** [comment]
Yes iso, when choosing ext4 format is set properly, when you select an
btrfs error: ERROR - ==> ERROR: file not found: `fsck.btrfs'
ERROR - ==> WARNING: No fsck helpers found. fsck will not be run on boot.

ERROR - ==> WARNING: errors were encountered during the build. The image
may not be complete.
ERROR - arch-chroot /mnt mkinitcpio -p linux

2016-10-07 13:54 GMT+00:00 arch3y notifications@github.com:

**Comment by archey** [comment]
We are working on testing this, we will update you soon.

**Comment by archey** [comment]
@ahtss  Seems like a common arch issue going on for years, https://bbs.archlinux.org/viewtopic.php?id=139370.

**Comment by xorond** [comment]
Closing this issue since it's an upstream problem.
